### PR TITLE
Add --cache flag to speed-up batch/repeat compression

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by lep** [comment]
Thanks. Looks good so far, but that mkdir call only works under windows this way.
I have looked up what i think is the correct way to define a portable mkdir. I would merge your patch and then apply my own. I would like you to test it again with my patch applied.

**Comment by Slayer95** [comment]
Sure. I'll probably try it today. For reference, my entire build pipeline for 120 maps takes a whooping 10-12 hours without this flag, but it's just a bit under 3 hours with caching.

**Comment by lep** [comment]
Wow, that sounds interesting. Do you have a write-up about your setup? Is compressmpq still the biggest cost-factor even with cache?

**Comment by Slayer95** [comment]
> write-up about your setup? Is compressmpq still the biggest cost-factor even with cache?

https://www.hiveworkshop.com/threads/project-evergreen-backported-mechanics.351924/#post-3620441

So, my pipeline includes
- Building AMAI (unless cached)
- Custom-processing war3map.j and other files in a per-map basis. (~ 3 mins)
- Installing AMAI into each map. (~ 3 mins)
- SLK optimization (~ 10 mins)
- Zopfli optimization (``-c -t 2 -l custom_listfile``) (2 threads for 2 cores >,<) (~ 2+ hours)

So, yes, the longest time is taken by compressmpq, which I think is to be expected? Of which a significant chunk of time is spent compressing differing files, like shaders, w3i, or .doo. But most of the time was effectively cut off by using the cache.

**Comment by Slayer95** [comment]
I bet I could save 1 or 2 additional hours in my build by storing ``compressmpq`` cache keys as ``base64(subfilename + content_hash)`` instead of ``base64(subfilename)``. That would require some hashing implementation. Would you approve that idea? Also, which hash would be good?

PS. Confirmed that latest master inits the ``cache`` dir correctly in Windows.

**Comment by lep** [comment]
Yes, i would be open to a hash based cache. Something like sha256 ought to be fine. But personally i would take a hash function which has like a header-only implementation or something like that to make it easy to drop in.

I don't know your build pipeline but i would naively think that *most* assets stay the same build-to-build. So it feels like there is potential to optimize here.

**Comment by Slayer95** [comment]
> I don't know your build pipeline but i would naively think that most assets stay the same build-to-build. So it feels like there is potential to optimize here.

Definitely.

> Something like sha256 ought to be fine. But personally i would take a hash function which has like a header-only implementation or something like that to make it easy to drop in.

Since the cache entries already store the uncompressed contents byte-per-byte, I'd think a fash hash function would do the trick, e.g. murmur (not necessarily favoring that one, but that's the only one I remember off the top of my head).

However, storing the entire files and for every possible hash entails the risk of a rapid and unbounded increase of the cache size. In that case, the way to go would be to only cache the compressed data, and verify by decompressing, right? AFAIK, can ``miniz`` be used for that?

**Comment by lep** [comment]
I thought about hashing the uncompressed file and storing the compressed file under that hash.
You could `touch` those files, even if allready present in the cache to update it's timestamp. To clean up the cache just delete files older than whatever threshold one seems appropriate. Or delete the N oldest files, etc. But deleting should not be done in compressmpq.

I bet there are better cache designs for this space but this should be easy enough to implement while still have some control over the cache growth.

**Comment by Slayer95** [comment]
> I thought about hashing the uncompressed file and storing the compressed file under that hash.

That's also what I say. The extra verification step is to handle potential collisions. And, yea. Apparently ``tinfl_decompress`` does the job, in a streaming fashion potentially, even.

> You could touch those files, even if allready present in the cache to update it's timestamp.

Nice idea.

> But deleting should not be done in compressmpq.

Also agreed.

**Comment by lep** [comment]
With something like sha256 i wouldn't worry about collisions, tbh.

**Comment by Slayer95** [comment]
Well, that does make implementation easier for me.

**Pull request merged**
